import { api } from './api.js';
const $=id=>document.getElementById(id);let generation=0,busy=false,lastRows='';
function tick(){const now=new Date();$('today').textContent=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',month:'long',day:'numeric',weekday:'long'}).format(now);$('clock').textContent=new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now);}tick();setInterval(tick,1000);
function render(data){$('total').textContent=data.total+'명';$('present').textContent=data.present+'명';$('absent').textContent=(data.total-data.present)+'명';const fingerprint=JSON.stringify(data.rows);if(fingerprint===lastRows){$('sync').textContent='방금 갱신됨';return;}lastRows=fingerprint;$('rows').replaceChildren();const absent=data.rows.filter(row=>row.status==='absent');absent.forEach((row,i)=>{const tr=document.createElement('tr');[i+1,row.number,row.name].forEach(value=>{const td=document.createElement('td');td.textContent=value;tr.append(td);});const status=document.createElement('td');const badge=document.createElement('span');badge.className='absence-badge';badge.textContent='결석';status.append(badge);tr.append(status);const td=document.createElement('td'),button=document.createElement('button');button.className='mark-present';button.textContent='출석';button.setAttribute('aria-label',row.name+' 출석 처리');button.onclick=()=>update({...row,status:'present'},button);td.append(button);tr.append(td);$('rows').append(tr);});$('empty').hidden=absent.length>0;$('empty').textContent=data.total?'모두 출석했어요. 함께 읽기를 시작해 볼까요?':'등록된 학생이 없습니다. 아래에서 명단을 등록하세요.';$('sync').textContent='방금 갱신됨';}
function report(error){$('message').textContent=error.message;$('sync').textContent='갱신 실패 · 다시 시도';if(error.status===401)location.replace('/');}
async function refresh(){if(!$('classId').value||busy)return;const id=++generation,classId=$('classId').value;try{const data=await api('/api/teacher/attendance?classId='+encodeURIComponent(classId));if(id===generation)render(data);}catch(error){if(id===generation)report(error);}}
async function update(values,button){if(busy)return false;busy=true;++generation;button.disabled=true;$('classId').disabled=true;$('message').textContent='';try{const data=await api('/api/teacher/attendance',{...values,classId:$('classId').value});render(data);$('message').textContent='출결을 반영했습니다.';return true;}catch(error){report(error);return false;}finally{busy=false;button.disabled=false;$('classId').disabled=false;}}
$('manual').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));if(await update(values,e.submitter)){e.target.reset();e.target.elements.number.focus();}};
$('roster').onsubmit=async e=>{e.preventDefault();if(busy)return;const classId=$('classId').value;if(!classId)return;const students=new FormData(e.target).get('students').trim().split(/\r?\n/).map(line=>{const [number,...rest]=line.trim().split(/[\t ,]+/);return {number,name:rest.join(' ')};});busy=true;++generation;e.submitter.disabled=true;$('classId').disabled=true;try{await api('/api/teacher/roster',{classId,students});$('rosterMessage').textContent='명단을 등록했습니다. 학번과 이름이 일치하는 학생만 입장할 수 있습니다.';e.target.reset();}catch(error){$('rosterMessage').textContent=error.message;}finally{busy=false;e.submitter.disabled=false;$('classId').disabled=false;await refresh();}};
$('classId').onchange=()=>{++generation;lastRows='';$('rows').replaceChildren();for(const id of ['total','present','absent'])$(id).textContent='—';$('empty').hidden=true;$('manual').reset();$('roster').reset();$('message').textContent='';$('rosterMessage').textContent='';refresh();};$('refresh').onclick=refresh;$('logout').onclick=async()=>{try{await api('/api/teacher/logout',{});location.href='/';}catch(error){report(error);}};
try{const user=await api('/api/teacher/me');for(const group of user.classes.sort((a,b)=>a.name.localeCompare(b.name,'ko',{numeric:true}))){const option=new Option(group.name,group.id);$('classId').append(option);}if(!user.classes.length){$('message').textContent='담당 학급이 없습니다. 운영 담당자에게 학급 배정을 요청하세요.';document.querySelectorAll('form button').forEach(b=>b.disabled=true);}await refresh();setInterval(refresh,5000);}catch(error){report(error);}
