// Generated by tests/extract-word-targets.py from SWF up-state text and geometry.
import { WORD_READINGS } from './word-readings.js';
export const WORD_TARGETS = {
  "a": [
    {
      "reading": "あい",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "おおい",
      "x": 249.0,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "えい",
      "x": 292.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "うえ",
      "x": 504.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "いえ",
      "x": 549.95,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "ha": [
    {
      "reading": "はし",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "ひふ",
      "x": 545.95,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "ふね",
      "x": 498.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "へや",
      "x": 302.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "ほし",
      "x": 257.0,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "ka": [
    {
      "reading": "かお",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "こい",
      "x": 249.0,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "いけ",
      "x": 292.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "くき",
      "x": 504.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "きく",
      "x": 549.95,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "ma": [
    {
      "reading": "まち",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "みみ",
      "x": 549.95,
      "y": 236.0,
      "radius": 44.0
    },
    {
      "reading": "むね",
      "x": 504.95,
      "y": 414.95,
      "radius": 44.0
    },
    {
      "reading": "め",
      "x": 303.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "もも",
      "x": 253.0,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "na": [
    {
      "reading": "なつ",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "にく",
      "x": 544.95,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "いぬ",
      "x": 498.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "ねこ",
      "x": 304.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "のき",
      "x": 255.0,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "ra": [
    {
      "reading": "そら",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "とり",
      "x": 548.95,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "さる",
      "x": 503.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "れつ",
      "x": 302.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "ろく",
      "x": 251.0,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "sa": [
    {
      "reading": "あさ",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "そこ",
      "x": 249.0,
      "y": 237.0,
      "radius": 44.0
    },
    {
      "reading": "せかい",
      "x": 292.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "すし",
      "x": 504.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "しお",
      "x": 549.95,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "ta": [
    {
      "reading": "たかい",
      "x": 393.95,
      "y": 129.0,
      "radius": 44.0
    },
    {
      "reading": "ちかてつ",
      "x": 550.6,
      "y": 236.975,
      "radius": 44.2,
      "radiusY": 44.175
    },
    {
      "reading": "つくえ",
      "x": 504.95,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "てき",
      "x": 306.0,
      "y": 415.95,
      "radius": 44.0
    },
    {
      "reading": "とし",
      "x": 256.0,
      "y": 236.0,
      "radius": 44.0
    }
  ],
  "wa": [
    {
      "reading": "ほん",
      "x": 513.95,
      "y": 389.95,
      "radius": 44.0
    },
    {
      "reading": "わたし",
      "x": 274.55,
      "y": 390.95,
      "radius": 44.0
    },
    {
      "reading": "ほんをよむ",
      "x": 402.95,
      "y": 142.0,
      "radius": 71.0,
      "radiusY": 44.0
    }
  ],
  "ya": [
    {
      "reading": "ゆき",
      "x": 535.95,
      "y": 365.95,
      "radius": 44.0
    },
    {
      "reading": "やま",
      "x": 393.95,
      "y": 141.0,
      "radius": 44.0
    },
    {
      "reading": "ひよこ",
      "x": 260.0,
      "y": 363.95,
      "radius": 44.0
    }
  ]
};

export function wordTarget(rowId, index) {
  const word = WORD_TARGETS[rowId]?.[index];
  return word ? { ...word, id: `${rowId}-word-${index}`, ruby: WORD_READINGS[word.reading] || '' } : null;
}

