import test from 'node:test';
import assert from 'node:assert/strict';
import { once } from 'node:events';
import { createApp } from '../classroom-server.mjs';
import { openStore, hashPassword } from '../server/store.mjs';

test('roster validation, daily attendance, manual corrections and teacher isolation', async t => {
  const db=openStore(':memory:');
  for(const id of ['a','b']) {
    db.prepare('INSERT INTO classes VALUES (?,?,?)').run(id,id,'unused');
    db.prepare('INSERT INTO teachers VALUES (?,?,?)').run(id,id,hashPassword('password-'+id));
    db.prepare('INSERT INTO permissions VALUES (?,?)').run(id,id);
  }
  const {server}=createApp({db});server.listen(0,'127.0.0.1');await once(server,'listening');
  t.after(async()=>{await new Promise(r=>server.close(r));db.close();});
  const base=`http://127.0.0.1:${server.address().port}`;
  const call=(path,data,cookie)=>fetch(base+path,{method:data?'POST':'GET',headers:{Origin:base,'Content-Type':'application/json',...(cookie?{Cookie:cookie}:{})},...(data?{body:JSON.stringify(data)}:{})});
  let response=await call('/api/login',{password:'password-a'});assert.equal(response.status,200);
  const cookie=response.headers.get('set-cookie').split(';')[0];
  assert.equal((await call('/api/login',{password:'wrong'})).status,401);
  const students=[{number:'20101',name:'김하루'},{number:'20102',name:'이소라'}];
  assert.equal((await call('/api/teacher/roster',{classId:'a',students},cookie)).status,200);
  assert.equal((await call('/api/teacher/roster',{classId:'b',students},cookie)).status,403);
  assert.equal((await call('/api/teacher/attendance?classId=a')).status,401);
  assert.equal((await call('/api/teacher/attendance?classId=b',null,cookie)).status,403);
  const read=async()=> (await call('/api/teacher/attendance?classId=a',null,cookie)).json();
  assert.equal((await read()).total,2);assert.equal((await read()).present,0);
  assert.equal((await call('/api/join',{number:'20101',name:'틀린 이름',consent:true})).status,400);
  assert.equal((await call('/api/join',{number:'99999',name:'김하루',consent:true})).status,400);
  const join=()=>call('/api/join',{...students[0],consent:true});
  assert.equal((await join()).status,200);assert.equal((await join()).status,200);
  assert.equal((await read()).present,1);
  const mark=status=>call('/api/teacher/attendance',{classId:'a',...students[0],status},cookie);
  assert.equal((await mark('absent')).status,200);assert.equal((await read()).present,0);
  assert.equal((await mark('present')).status,200);assert.equal((await read()).present,1);
  assert.equal((await mark('invalid')).status,400);
  assert.equal((await call('/api/teacher/attendance',{classId:'a',number:'20101',name:'wrong',status:'present'},cookie)).status,400);
  db.prepare('UPDATE attendance SET day=?').run('2000-01-01');assert.equal((await read()).present,0);
  const conflict = await call('/api/teacher/roster',{classId:'a',students:[{number:'20103',name:'추가'},{number:'20101',name:'다른 이름'}]},cookie);
  assert.equal(conflict.status,400);
  assert.match((await conflict.json()).error,/20101는 이미 '김하루'로 등록되어 있습니다. '다른 이름'으로는 등록할 수 없습니다/);
  const unchanged = await read();
  assert.equal(unchanged.total,2);
  assert.equal(unchanged.rows.find(row => row.number==='20101').name,'김하루');
  assert.equal((await call('/api/teacher/roster',{classId:'a',students:[{number:'20101',name:'김하루'},{number:'20101',name:'김하루'}]},cookie)).status,200);
  assert.equal((await read()).total,2);
  assert.equal((await call('/api/teacher/roster',{classId:'a',students:[{number:'20104',name:'김하루'},{number:'20105',name:'김하루'}]},cookie)).status,200);
  assert.equal((await read()).total,4);
  assert.equal((await call('/api/join',{number:'20104',name:'김하루',consent:true})).status,200);
  assert.equal((await call('/api/join',{number:'20105',name:'김하루',consent:true})).status,200);
  db.prepare('INSERT INTO roster VALUES (?,?,?)').run('b','20701','다른 반');
  response=await call('/api/join',{number:'20701',name:'다른 반',consent:true});assert.equal(response.status,200);
  const studentCookie=response.headers.get('set-cookie').split(';')[0];
  assert.equal((await (await call('/api/me',null,studentCookie)).json()).classId,'b');
  assert.equal((await call('/api/teacher/attendance?classId=b',null,studentCookie)).status,401);
  const wrongDelete = await call('/api/teacher/roster/delete',{classId:'a',students:[{number:'20102',name:'다른 사람'}]},cookie);
  assert.equal(wrongDelete.status,400);
  assert.match((await wrongDelete.json()).error,/삭제할 수 없습니다/);
  assert.equal((await read()).rows.some(row => row.number==='20102'),true);
  db.prepare('INSERT INTO attempts VALUES (?,?,?,?,?,?,?,?,?,?,?)').run('keep-history','teacher','a','20102','이소라','a','あ','あ',100,1,new Date().toISOString());
  assert.equal((await call('/api/teacher/roster/delete',{classId:'a',students:[{number:'20102',name:'이소라'}]},cookie)).status,200);
  assert.equal((await read()).rows.some(row => row.number==='20102'),false);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM attempts WHERE number=?').get('20102').n,1);
  assert.equal((await call('/api/teacher/roster/delete',{classId:'b',students:[{number:'20104'}]},cookie)).status,403);
});
