import test from 'node:test';
import assert from 'node:assert/strict';
import { recognizedHiragana } from '../server/hiragana.mjs';
import { wordTarget } from '../js/word-targets.js';
import { countMorae, expandLongVowels, promptedReading } from '../js/kana.js';
import { assess } from '../js/score.js';

test('recognized words are rendered as actual hiragana, not copied from the target', async () => {
  const word=wordTarget('a',0);
  assert.equal(await recognizedHiragana('愛',word),'あい');
  assert.equal(await recognizedHiragana('アイ',word),'あい');
  assert.equal(await recognizedHiragana('猫',word),'ねこ');
  assert.equal(await recognizedHiragana('お母さん',{reading:'おかあさん'}),'おかあさん');
  assert.equal(await recognizedHiragana('ABC',word),null);
  assert.equal(await recognizedHiragana('はい',word),'あい');
  assert.equal(await recognizedHiragana('ハイ',word),'あい');
  assert.equal(promptedReading('あい','はい'),'あい');
  assert.equal(await recognizedHiragana('えい',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('エイ',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('えー',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('에이',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('へ',wordTarget('a',2)),'へ');
  assert.equal(await recognizedHiragana('ええ',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('え',wordTarget('a',2)),'えい');
  assert.equal(await recognizedHiragana('ひ',wordTarget('a',2)),'ひ');
  assert.equal(await recognizedHiragana('はい',wordTarget('ha',0)),'はい');
  assert.equal(await recognizedHiragana('いいえ',wordTarget('a',4)),'いえ');
  assert.equal(await recognizedHiragana('イイエ',wordTarget('a',4)),'いえ');
  assert.equal(await recognizedHiragana('いいえ',wordTarget('a',2)),'いいえ');
  assert.equal(await recognizedHiragana('ほしい',wordTarget('ha',4)),'ほし');
  assert.equal(await recognizedHiragana('欲しい',wordTarget('ha',4)),'ほし');
  assert.equal(await recognizedHiragana('レッツ',wordTarget('ra',3)),'れつ');
  assert.equal(await recognizedHiragana('れっつ',wordTarget('ra',3)),'れつ');
  assert.equal(promptedReading('え','ええ'),'え');
  assert.equal(promptedReading('え','絵'),'え');
  assert.equal(promptedReading('え','あい'),'あい');
  assert.equal(promptedReading('え','えい'),'えい');
  assert.equal(promptedReading('え','えんぴつ'),'えんぴつ');
  assert.equal(promptedReading('え','こんにちは'),'こんにちは');
  assert.equal(await recognizedHiragana('えんぴつ',wordTarget('a',2)),'えんぴつ');
  assert.equal(await recognizedHiragana('あい',wordTarget('a',2)),'あい');
  assert.equal(promptedReading('え','에~'),'え');
  assert.equal(promptedReading('え','에에'),'え');
  assert.equal(promptedReading('えい','えい'),'えい');
  assert.equal(promptedReading('えい','エイ'),'えい');
  assert.equal(promptedReading('えい','えー'),'えい');
  assert.equal(promptedReading('えい','에이'),'えい');
  assert.equal(promptedReading('えい','애이'),'えい');
  assert.equal(promptedReading('えい','에에'),'えい');
  assert.equal(promptedReading('えい','ええ'),'えい');
  assert.equal(promptedReading('えい','え'),'えい');
  assert.equal(promptedReading('えい','에'),'えい');
  assert.equal(promptedReading('えい','へ'),'へ');
  assert.equal(promptedReading('て','테'),'て');
  assert.equal(promptedReading('て','테에~'),'て');
  assert.equal(promptedReading('て','테에에'),'て');
  assert.equal(promptedReading('て','で'),'て');
  assert.equal(promptedReading('て','てえ'),'て');
  assert.equal(promptedReading('め','めえ'),'め');
  assert.equal(promptedReading('あい','で'),'で');
  assert.equal(promptedReading('に','니'),'に');
  assert.equal(promptedReading('に','니이~'),'に');
  assert.equal(promptedReading('に','2'),'に');
  assert.equal(promptedReading('に','二'),'に');
  assert.equal(promptedReading('に','ん'),'に');
  assert.equal(promptedReading('に','んい'),'に');
  assert.equal(promptedReading('に','ニー'),'に');
  assert.equal(promptedReading('に','にほん'),'に');
  assert.equal(promptedReading('に','には'),'に');
  assert.equal(promptedReading('に','ね'),'ね');
  assert.equal(promptedReading('に','る'),'に');
  assert.equal(promptedReading('に','ルー'),'に');
  assert.equal(promptedReading('に','り'),'に');
  assert.equal(promptedReading('に','リー'),'に');
  assert.equal(promptedReading('と','る'),'る');
  assert.equal(promptedReading('と','り'),'り');
  assert.equal(promptedReading('え','にほん'),'にほん');
  assert.equal(promptedReading('え','ん'),'ん');
  assert.equal(promptedReading('え','2'),'2');
  assert.equal(promptedReading('め','메에~'),'め');
  assert.equal(promptedReading('ひ','테에'),'테에');
  assert.equal(promptedReading('ひ','い'),'ひ');
  assert.equal(promptedReading('ひ','いい'),'ひ');
  assert.equal(promptedReading('ひ','ひと'),'ひ');
  assert.equal(promptedReading('ひ','び'),'ひ');
  assert.equal(promptedReading('ひ','히'),'ひ');
  assert.equal(promptedReading('ひ','hi'),'ひ');
  assert.equal(promptedReading('ひ','はい'),'はい');
  assert.equal(promptedReading('ひ','ふ'),'ひ');
  assert.equal(promptedReading('ひ','ふう'),'ひ');
  assert.equal(promptedReading('ひ','フー'),'ひ');
  assert.equal(promptedReading('ひ','ふね'),'ふね');
  assert.equal(promptedReading('め','ふ'),'ふ');
  assert.equal(promptedReading('め','い'),'い');
  assert.equal(promptedReading('のき','노키'),'のき');
  assert.equal(promptedReading('まち','마치'),'まち');
  assert.equal(promptedReading('みみ','미미'),'みみ');
  assert.equal(promptedReading('め','메'),'め');
  assert.equal(promptedReading('め','ひ'),'ひ');
  assert.equal(promptedReading('みみ','み'),'みみ');
  assert.equal(promptedReading('みみ','みー'),'みみ');
  assert.equal(promptedReading('みみ','みみず'),'みみ');
  assert.equal(promptedReading('め','み'),'み');
  assert.equal(await recognizedHiragana('軒',wordTarget('na',4)),'のき');
  assert.equal(await recognizedHiragana('町',wordTarget('ma',0)),'まち');
  assert.equal(await recognizedHiragana('待ち',wordTarget('ma',0)),'まち');
  assert.equal(await recognizedHiragana('耳',wordTarget('ma',1)),'みみ');
  assert.equal(await recognizedHiragana('敵',wordTarget('ta',3)),'てき');
  assert.equal(await recognizedHiragana('都市',wordTarget('ta',4)),'とし');
  assert.equal(await recognizedHiragana('目',wordTarget('ma',3)),'め');
});

test('long-vowel notation preserves morae but does not claim acoustic timing assessment', async () => {
  const word=wordTarget('a',1);
  assert.equal(await recognizedHiragana('多い',word),'おおい');
  assert.equal(await recognizedHiragana('オーイ',word),'おおい');
  assert.equal(await recognizedHiragana('おい',word),'おい');
  assert.equal(countMorae('おおい'),3);
  assert.equal(countMorae('おかあさん'),5);
  assert.equal(countMorae('きゃく'),2);
  assert.equal(countMorae('きって'),3);
  assert.equal(expandLongVowels('コーコー','こうこう'),'こうこう');
  assert.equal(promptedReading('のき','のんき'),'のき');
  assert.equal(promptedReading('のき','のーき'),'のき');
  assert.equal(promptedReading('のき','ノーキ'),'のき');
  assert.equal(promptedReading('のき','おき'),'おき');
  assert.equal(promptedReading('のき','ろっきい'),'のき');
  assert.equal(promptedReading('のき','ロッキー'),'のき');
  assert.equal(promptedReading('れつ','ろっきい'),'ろっきい');
  assert.ok(assess('おい','おーい').score < 100);
  assert.equal(await recognizedHiragana('のんき',wordTarget('na',4)),'のき');
  assert.equal(await recognizedHiragana('ノーキ',wordTarget('na',4)),'のき');
  // A transcript cannot reveal whether two お were separated or sustained.
  assert.equal(assess('おおい','おおい').score,100);
});
